version: '3.1'

services:
  tg-bot:
    build: ./Bot
    ports:
      - 3000:3000
    depends_on:
      - postgres
      
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
    volumes:
      - ./db-create/create_tables.sql:/docker-entrypoint-initdb.d/database-seed.sql
      - ./db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7
    restart: always
    user: "${UID}:${GID}"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "16543:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres